### ISSUE TITLE
what template you have used to generate the docs for this project?

### ISSUE THREAD

**Issue by powercoder23** [arminbhy/reactator#4]
Hi @arminbhy 

I have a requirement to do a documentation for our project, i  have been through your documentation  on [http://arminbhy.github.io/reactator/index.html](url) at the bottom i had seen it is generated using JSdoc i like that style.

Can  you pleae help me with the name of template you are using to generate documentation ?

Thanks,
Dhiraj Gupta

**Comment by arminbhy** [comment]
@powercoder23 its the default jsdoc. Checkout https://github.com/arminbhy/reactator/blob/master/package.json

```
"scripts": {
  "doc": "jsdoc reactator -r",
},
"devDependencies": {
  "jsdoc": "^3.4.0",
}
```
